import { type SpecKey } from "./spec-files.js";

export type BlueprintMode = "fe" | "backend" | "fullstack";

/**
 * Which spec artifacts `forge blueprint` auto-scaffolds for each mode.
 * `brief`/`prd` and `tasks`/`testcases` are universal — `schema` only makes
 * sense where a data layer is being built. `mockup` is deliberately absent
 * from every mode: it's never auto-generated by `blueprint`, only by running
 * `forge mockup <feature>` on demand (or by dropping in a design export) —
 * see OPTIONAL_SPEC_KEYS in spec-files.ts, which `forge verify` still checks
 * for regardless of mode.
 */
export const MODE_ARTIFACTS: Record<BlueprintMode, SpecKey[]> = {
  fe: ["brief", "prd", "contract", "tasks", "testcases"],
  backend: ["brief", "prd", "schema", "contract", "tasks", "testcases"],
  fullstack: ["brief", "prd", "schema", "contract", "tasks", "testcases"],
};

export function isValidMode(mode: string): mode is BlueprintMode {
  return mode === "fe" || mode === "backend" || mode === "fullstack";
}
